server:
  port: 9090

spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test_kafka_books
    username: postgres
    password: pwd
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.xml
